### ISSUE TITLE
запуск программы 

### ISSUE THREAD

**Issue by georgiyba** [ExpressApp/pybotx#383]
добрый день, подскажите как запустить программу?
так как при запуске ошибок нет но программа завершает работу

**Comment by kutuzov13** [comment]
Добрый день! Можете подробней описать вашу проблему.
Какой результат вы хотите получить?
Как выглядит ваша ошибка?

**Comment by georgiyba** [comment]
Можем перейти общение по электронной почте pms183_bashinskijgn@esrr.ru?

**Comment by kutuzov13** [comment]
К сожалению мы не дождались от вас ответа. Мы закроем это issue. Если у вас появятся вопросы просим вам создать его заново
