### ISSUE TITLE
Конфликт зависимостей httpx в библиотеках pybotx и gigachat

### ISSUE THREAD

**Issue by ezhkovskii** [ExpressApp/pybotx#427]
Здравствуйте. Хочу установить библиотеку gigachat, но poetry возвращает ошибку. Как это исправить?

![image](https://github.com/ExpressApp/pybotx/assets/51490864/8b9a9abe-7dd8-4d4f-9e7c-66ca37e6cf77)

**Comment by kutuzov13** [comment]
Здравствуйте!
В версии pybotx 0.60.3 обновлена зависимость httpx до ^0.25

**Comment by ezhkovskii** [comment]
> Здравствуйте! В версии pybotx [0.60.3](https://github.com/ExpressApp/pybotx/releases/tag/0.60.3) обновлена зависимость httpx до ^0.25

Спасибо. Бот не запускался с версией httpx=0.25.1, с версией 0.25.0 запустился.
![image](https://github.com/ExpressApp/pybotx/assets/51490864/c5ebb74a-12c2-4432-8183-aa1ff96f9260)
